### PR TITLE
qt-build-utils: when using frameworks add QT_INSTALL_LIBS explicitly

### LINKED ISSUE #885: QtCore not found.
system : macos 
buildIDE: vscode 
.vscode/settings.json:
```
"cmake.environment": {
        // "Qt6_DIR": "", ///opt/homebrew/opt/qt@5/lib/cmake/Qt5",
        "Qt5_DIR": "/opt/homebrew/Cellar/qt@5/5.15.12_1/lib/cmake/Qt5",
        "USE_QT5": "true",
        "RUSTFLAGS": "-C link-arg=-F/opt/homebrew/Cellar/qt@5/5.15.12_1/lib"
    },
```

```
[main] Building folder: cxx-qt 
[build] Starting build
[proc] Executing command: /opt/homebrew/bin/cmake --build /Users/allen/Projects/RustProjects/cxx-qt/build --config Debug --target _cargo-build_qml-features --
[build] [1/2   0% :: 0.002] cd /Users/allen/Projects/RustProjects/cxx-qt/examples/qml_features/rust && /Applications/CMake.app/Contents/bin/cmake -E env CXXQT_EXPORT_DIR=/Users/allen/Projects/RustProjects/cxx-qt/build/examples/qml_features/cxxqt DYLD_FRAMEWORK_PATH=/opt/homebrew/Cellar/qt@5/5.15.12_1/lib QMAKE=/opt/homebrew/Cellar/qt@5/5.15.12_1/bin/qmake CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=/usr/bin/clang CC_aarch64-apple-darwin=/usr/bin/clang CXX_aarch64-apple-darwin=/usr/bin/clang++ SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk CORROSION_BUILD_DIR=/Users/allen/Projects/RustProjects/cxx-qt/build/examples/qml_features CARGO_BUILD_RUSTC=/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc /Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/bin/cargo rustc --lib --target=aarch64-apple-darwin --package qml-features --manifest-path /Users/allen/Projects/RustProjects/cxx-qt/examples/qml_features/rust/Cargo.toml --target-dir /Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build -- -Cdefault-linker-libraries=yes
[build]    Compiling cxx-qt-lib v0.6.0 (/Users/allen/Projects/RustProjects/cxx-qt/crates/cxx-qt-lib)
[build]    Compiling qml-features v0.1.0 (/Users/allen/Projects/RustProjects/cxx-qt/examples/qml_features/rust)
[build] error: linking with `/usr/bin/clang` failed: exit status: 1
[build]   |
[build]   = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/allen/.cargo/bin:/Users/allen/Library/Application Support/JetBrains/Toolbox/scripts:/Users/allen/Library/Python/3.9/bin" VSLANG="1033" ZERO_AR_DATE="1" "/usr/bin/clang" "-arch" "arm64" "/var/folders/hw/lc023pr55psdqktjg68xvnkw0000gn/T/rustc7cGQY5/symbols.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.10fl17pzfgknotu.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.119okv1xmy7z81f6.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.137xat5v19szbkn0.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.15oph1vhrzhh5e5j.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.19opgb164thgeyxk.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.1vlp0hyqz47obvqu.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.1yhg74qrm5jbn57.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.26tes9igtz8fy7rn.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.2mfoke3mrp14psgs.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.2xsado67lvou67qs.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.2zb7b71tju74uh5j.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.37xis5uwom24c582.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.3qh0u66rpovuphck.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.4186phjz8kddzw0h.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.42i2ewundsav9ojs.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.45d9edr6wy3brpeh.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.4aqs871owq9ftsf1.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.4zbmzfjwshprgoiz.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.4zm0s84o8zrdyxpo.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.55605lsdx0j8mjk3.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.55mmkitcjyl348i7.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.5663x8hp4g2zm7jf.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.59c517g8ydpmusil.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.xhcy1h0fk613fhe.rcgu.o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7.4qr33kompxeqtcjw.rcgu.o" "-L" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/deps" "-L" "/opt/homebrew/Cellar/qt@5/5.15.12_1/lib" "-L" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-cd4fe937a4be2c39/out" "-L" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-201f66f53e1e6176/out" "-L" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/link-cplusplus-71603c78c2dde3e1/out" "-L" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcxx_qt_lib_headers-d9912cca892c1c19.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcxx_qt_build-6ab1336d900c684d.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libversion_check-9f51aa7577df62b5.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcxx_qt-d2c539d1a4753f86.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libstatic_assertions-21ebe0eb3cea606d.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcxx-0dae514a5f69b4e8.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/liblink_cplusplus-29d675dabc421268.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libqt_build_utils-906dd61ff2dbfcbc.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libversions-8466793749c2eea6.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libnom-718756c2487eced8.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libmemchr-e6b5ebc697c65687.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libitertools-e621136652a36976.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libeither-f70f4bfdd6077160.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcc-4f7e5addbf99ef3e.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libjobserver-dd4b614b2cf16aea.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/liblibc-dd2450870a8e46be.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcxx_gen-5eee1925fa27fac5.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcxx_qt_gen-8d441a361f4b6960.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libclang_format-089b44882994e1ab.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libthiserror-dd35499ccfe2017d.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libconvert_case-35c30cdcabc87c2a.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libunicode_segmentation-7d3ed2ca008d237f.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libsyn-ac3b92559e3bce53.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libquote-f7d359d29bfc9b4a.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libcodespan_reporting-16803727eb35ee92.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libunicode_width-16a1984432142341.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libtermcolor-3d23a97142594491.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libproc_macro2-950e5ceb51725b27.rlib" "/Users/allen/Projects/RustProjects/cxx-qt/build/cargo/build/debug/deps/libunicode_ident-2260bb06186abcf3.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libproc_macro-c7150b0669ad7a0f.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-4f192af08beaa759.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_unwind-401344856f0fc3c5.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-9e012890a70780c2.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-60338fe528589910.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-a2e883cf5bcf6347.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-df8440ef641907f8.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-fa2288bf7728f91c.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-f39c850853dd7dfe.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-c5b1930e10569ddd.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-96bad2fc8f58f610.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-06eec439eca0e252.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-023007819562a373.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-7254491d238c3b3e.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-9f474e4309122405.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-0bfd536a501ea558.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-d56621fef414e9f8.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-60d6843fd08e9533.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-62a9b4d83244cb2b.rlib" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-4010f8e9d1f7f9aa.rlib" "-framework" "QtCore" "-framework" "DiskArbitration" "-framework" "IOKit" "-lc++" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/Users/allen/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/allen/Projects/RustProjects/cxx-qt/build/./cargo/build/debug/build/cxx-qt-lib-6020208f1a041cc7/build_script_build-6020208f1a041cc7" "-Wl,-dead_strip" "-nodefaultlibs"
[build]   = note: ld: framework 'QtCore' not found
[build]           clang: error: linker command failed with exit code 1 (use -v to see invocation)
[build]           
[build] 
[build] error: linking with `/usr/bin/clang` failed: exit status: 1
[build]   |
```

### PR DESCRIPTION
**Pull request by ahayzen-kdab**
Closes #885

### CODE REVIEW

File: crates/qt-build-utils/src/lib.rs [hunk 1]
```diff
@@ -484,6 +488,16 @@ impl QtBuild {
...
         }
 
+        // If we have found at least one framework for the Qt modules then
+        // add the QT_INSTALL_LIBS as a framework link search path
+        //
+        // Note that leaving the kind empty should default to all,
+        // but this doesn't appear to find frameworks in all situations
+        // https://github.com/KDAB/cxx-qt/issues/885
+        if found_framework {
+            println!("cargo:rustc-link-search=framework={lib_path}");
```
Comment (ahayzen-kdab) [inline crates/qt-build-utils/src/lib.rs:498]: needs testing

Comment (ahayzen-kdab) [reply crates/qt-build-utils/src/lib.rs:498]: In a framework system i wonder if there ever are normal libraries in the `QT_INSTALL_LIBS` path or if there are only frameworks ? As the docs state that using `framework=` means that `Only search for macOS frameworks in this directory.` which would mean we could lose those?

Comment (ahayzen-kdab) [reply crates/qt-build-utils/src/lib.rs:498]: Appears that folder is mostly frameworks, only a few static libs (see the issue).

**Review by LeonMatthesKDAB — APPROVED** [review]
