### PR TITLE
cxx-qt-build: unset bundle for link modifiers

### LINKED ISSUE #519: error: link modifiers combination `+bundle,+whole-archive` is unstable when generating rlibs
```
Compiling qml-features v0.1.0 (/home/cschwan/kde/cxx-qt/examples/qml_features/rust)
error: link modifiers combination `+bundle,+whole-archive` is unstable when generating rlibs
```

tested with rust from the fedora repo and from rustup.

### PR DESCRIPTION
**Pull request by ahayzen-kdab**
Otherwise the build fails with

link modifiers combination `+bundle,+whole-archive` is unstable when generating rlibs

Closes #519

### CODE REVIEW

File: crates/cxx-qt-build/src/lib.rs [hunk 1]
```diff
@@ -408,6 +408,9 @@ impl CxxQtBuilder {
         // to avoid bloating the binary.
         let mut cc_builder_whole_archive = cc::Build::new();
         cc_builder_whole_archive.link_lib_modifier("+whole-archive");
+        // We need to set -bundle otherwise the compiler fails with
+        // link modifiers combination `+bundle,+whole-archive` is unstable when generating rlibs
```
Comment (Be-ing) [inline crates/cxx-qt-build/src/lib.rs:412]:
```suggestion
        // link modifiers combination `+bundle,+whole-archive` is unstable when generating rlibs
        // https://github.com/rust-lang/rust/issues/108081
```

Comment (ahayzen-kdab) [reply crates/cxx-qt-build/src/lib.rs:412]: Done

**Review by Be-ing — APPROVED** [review]
